import type { UmaCharacter } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) return { imageUrl: '', imageHint: 'placeholder', description: 'No description available.' };
    return { imageUrl: img.imageUrl, imageHint: img.imageHint, description: img.description };
}

export const presetCharacters: UmaCharacter[] = [
  {
    id: 'special-week',
    name: 'Special Week',
    ...getImage('special-week'),
    baseStats: { speed: 50, stamina: 50, technique: 50 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Normal',
    comfortMin: 40,
    comfortMax: 60,
    trait: { name: 'Balanced', description: 'Gains stats evenly across all areas.' },
  },
  {
    id: 'silence-suzuka',
    name: 'Silence Suzuka',
    ...getImage('silence-suzuka'),
    baseStats: { speed: 65, stamina: 40, technique: 45 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Calm',
    comfortMin: 50,
    comfortMax: 70,
    trait: { name: 'Pacesetter', description: 'Gains more Speed when in the sweet zone.' },
  },
  {
    id: 'tokai-teio',
    name: 'Tokai Teio',
    ...getImage('tokai-teio'),
    baseStats: { speed: 55, stamina: 45, technique: 60 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Normal',
    comfortMin: 45,
    comfortMax: 65,
    trait: { name: 'Prodigy', description: 'Gains significantly more Technique from Good Stride.' },
  },
  {
    id: 'vodka',
    name: 'Vodka',
    ...getImage('vodka'),
    baseStats: { speed: 60, stamina: 40, technique: 40 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Fiery',
    comfortMin: 35,
    comfortMax: 55,
    trait: { name: 'Powerhouse', description: 'Gains a small amount of speed even when Overstraining.' },
  },
  {
    id: 'gold-ship',
    name: 'Gold Ship',
    ...getImage('gold-ship'),
    baseStats: { speed: 45, stamina: 60, technique: 35 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Fiery',
    comfortMin: 30,
    comfortMax: 70,
    trait: { name: 'Unpredictable', description: 'Stamina loss from Overstrain is reduced.' },
  },
  {
    id: 'daiwa-scarlet',
    name: 'Daiwa Scarlet',
    ...getImage('daiwa-scarlet'),
    baseStats: { speed: 55, stamina: 55, technique: 50 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Normal',
    comfortMin: 40,
    comfortMax: 60,
    trait: { name: 'Steady', description: 'Loses less Tension per second when not tapping.' },
  },
  {
    id: 'rice-shower',
    name: 'Rice Shower',
    ...getImage('rice-shower'),
    baseStats: { speed: 40, stamina: 65, technique: 55 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Calm',
    comfortMin: 35,
    comfortMax: 50,
    trait: { name: 'Late Burst', description: 'Score bonus for Good Stride is higher in the last 3 seconds.' },
  },
  {
    id: 'haru-urara',
    name: 'Haru Urara',
    ...getImage('haru-urara'),
    baseStats: { speed: 30, stamina: 70, technique: 40 },
    level: 1,
    xp: 0,
    xpToNextLevel: 100,
    temperament: 'Calm',
    comfortMin: 25,
    comfortMax: 45,
    trait: { name: 'Heart of Gold', description: 'Gains more Stamina when Underpace.' },
  },
];
